AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless log storage and analysis - liquidlabs::logscape
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
    - '*/*'
Resources:
  LogscapeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java8
      CodeUri: s3://logscape-runtime-test/03eb33df2f4400a908d85194bce092b7
      MemorySize: 512
      Policies: AWSLambdaFullAccess
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
Outputs:
  LogscapeApi:
    Description: The REST API for the web-frontend
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
    Export:
      Name: LogscapeApi
